export const SOCIAL_MEDIA: MenuItemProps[] = [
  {
    title: 'Email',
    href: `mailto:${socialAccounts.email}`,
    icon: <EmailIcon size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Contact: Email',
    className: '!bg-green-600 border border dark:border-neutral-700',
    type: 'Link',
  },
  {
    title: 'Twitter',
    href: socialAccounts.x,
    icon: <TwitterIcon size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Social: Twitter',
    className: '!bg-sky-500 border border dark:border-neutral-700',
    type: 'Link',
  },
  {
    title: 'Instagram',
    href: socialAccounts.instagram,
    icon: <InstagramIcon size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Social: Instagram',
    className: '!bg-orange-700 border border dark:border-neutral-700',
    type: 'Link',
  },
  {
    title: 'Github',
    href: socialAccounts.github,
    icon: <GithubIcon size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Social: Github',
    className: '!bg-black border border dark:border-neutral-700',
    type: 'Link',
  },
  {
    title: 'Google Scholar',
    href: socialAccounts.googlescholar, // Replace with your ID
    icon: <SiGooglescholar size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Social: Google Scholar',
    className: '!bg-blue-700 border border dark:border-neutral-700',
    type: 'Link',
  },
  {
    title: 'Linkedin',
    href: socialAccounts.linkedin,
    icon: <LinkedinIcon size={iconSize} />,
    isShow: true,
    isExternal: true,
    eventName: 'Social: Linkedin',
    className: '!bg-blue-500 border border dark:border-neutral-700',
    type: 'Link',
  },
].filter((item) => !!item.href);
